[package]
name = "Raton3d-Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi-rusb = "1.3.2"
parse_int = "0.6.0"